import Head from "next/head";

export default function Conclusion() {
    return (
        <div>
            <Head>
                <title>Conclusion</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>

            <main>
                <h1>
                    Conclusion
                </h1>
            </main>
        </div>
    )
}