import Head from "next/head";
import {
  Container,
  Grid,
  List,
  ListItemButton,
  ListItemIcon,
  ListItemText,
  ListSubheader,
  Box,
} from "@mui/material";
import ArrowRightIcon from "@mui/icons-material/ArrowRight";
import { useRouter } from "next/router";
import MenuPres from "../components/Presentation/MenuPres";
import MenuPresItem from "../components/Presentation/MenuPresItem";

export default function Introduction() {
  const router = useRouter();
  return (
    <Container>
      <Head>
        <title>Creation</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Grid container>
          <Grid item xs={8}>
            <Container>
              <Box style={{ height: "100vh" }}>
                <h1 id="1">Comment créer une PWA ?</h1>
                <p>
                  Afin de pouvoir installer une PWA cette dernière va devoir
                  remplir certains critères sans quoi il sera impossible de
                  l’installer. Il reste à noter que des différences de critères
                  d’installation peuvent être observés en fonction du navigateur
                  utilisé.
                </p>
              </Box>
              <Box style={{ height: "100vh" }}>
                <h2 id="2">La PWA ne doit pas déjà être installée</h2>
                <p>
                  Tout d’abord afin d’installer une PWA elle ne doit pas déjà
                  être présente sur la session active ou sur l’ordinateur. Et
                  ceci dans l’optique d’éviter plusieurs fois la même
                  application.
                </p>
              </Box>
              <Box style={{ height: "100vh" }}>
                <h2 id="3">Heuristiques d’engagement utilisateurs</h2>
                <p>
                  Dans un second temps l’installation de l’application
                  nécessiter de valider les heuristiques d’engagement
                  utilisateurs (user engagement heuristics). Elles sont au
                  nombre de deux et vont permettre de vérifier que l’utilisateur
                  a bien déjà utilisé l’application. Premièrement l’utilisateur
                  doit avoir interagit avec la page au moins une fois. Et
                  deuxièmement il doit avoir utilisé l’application pour au moins
                  30 secondes.
                </p>
              </Box>
              <Box style={{ height: "100vh" }}>
                <h2 id="4">Connection avec le serveur sécurisée</h2>
                <p>
                  Dans un souci de sécurité et de fiabilité l’application doit
                  être fournie via une connexion sécurisée en HTTPS.{" "}
                </p>
              </Box>
              <Box style={{ height: "100vh" }}>
                <h2 id="5">Manifest</h2>
                <p>
                  Ensuite afin de permettre au navigateur ainsi qu’au système
                  d’exploitation de savoir comment installer l’application il va
                  être nécessaire de mettre à disposition un manifest (web app
                  manifest) qui va contenir des informations supplémentaires sur
                  l’application. Parmi les champs les plus utilisés dans ce
                  manifeste il va y avoir le nom de l’application, l’icône sous
                  laquelle va être représentée la PWA, l’url utilisée lors du
                  lancement de l’application et enfin le mode d’affichage de la
                  fenêtre.
                </p>
              </Box>
              <Box style={{ height: "100vh" }}>
                <h2 id="6">Service Worker</h2>
                <p>
                  Et enfin l’application doit mettre à disposition un service
                  Worker pour permettre à l’application d’être utilisée en mode
                  hors ligne. Nous ne reviendrons pas sur son fonctionnement
                  déjà évoqué ci-dessus.
                </p>
              </Box>
            </Container>
          </Grid>
          <Grid item xs={4}>
            <Box
              style={{
                position: "sticky",
                top: "10px",
              }}
            >
                <MenuPres title="Création d'une PWA">
                    <MenuPresItem content="test" linkedElement="#1"/>
                </MenuPres>
            </Box>
          </Grid>
        </Grid>
      </main>
    </Container>
  );
}
