import styles from "../styles/Home.module.css";
import Head from "next/head";

export default function Introduction() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Creation</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Creation
                </h1>
            </main>
        </div>
    )
}