import Head from "next/head";
import {Box, Container} from "@mui/material";
import {useRouter} from "next/router";

export default function Introduction() {
    const router = useRouter();
    return (
        <div>
            <Head>
                <title>Creation</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>
            <main>
                <Container>
                    <Box height="100vh" onClick={() => {
                        router.push("/creation#slide2")
                    }}>
                        <h1 id="slide1">Comment créer une PWA ?</h1>
                        <p>
                            Afin de pouvoir installer une PWA cette dernière va devoir remplir
                            certains critères sans quoi il sera impossible de l’installer. Il
                            reste à noter que des différences de critères d’installation
                            peuvent être observés en fonction du navigateur utilisé.
                        </p>
                    </Box>
                    <Box height="100vh" onClick={() => {
                        router.push("/creation#slide3")
                    }}>
                        <h1 id="slide2">La PWA ne doit pas être deja presente sur le PC</h1>
                        <p>
                            Tout d’abord afin d’installer une PWA elle ne doit pas déjà être
                            présente sur la session active ou sur l’ordinateur. Et ceci dans
                            l’optique d’éviter plusieurs fois la même application.
                        </p>
                    </Box>
                    <Box height="100vh">
                        <h1 id="slide3">Heuristique engagement utilisateur</h1>
                        <p>
                            Dans un second temps l’installation de l’application nécessiter de
                            valider les heuristiques d’engagement utilisateurs (user
                            engagement heuristics). Elles sont au nombre de deux et vont
                            permettre de vérifier que l’utilisateur a bien déjà utilisé
                            l’application. Premièrement l’utilisateur doit avoir interagit
                            avec la page au moins une fois. Et deuxièmement il doit avoir
                            utilisé l’application pour au moins 30 secondes.
                        </p>
                    </Box>
                    <Box height="100vh">
                        <h1>Une connection HTTPS</h1>
                        <p>
                            Dans un souci de sécurité et de fiabilité l’application doit être
                            fournie via une connexion sécurisée en HTTPS.
                        </p>
                    </Box>
                    <Box height="100vh">
                        <h1>Manifest</h1>
                        <p>
                            Ensuite afin de permettre au navigateur ainsi qu’au système
                            d’exploitation de savoir comment installer l’application il va
                            être nécessaire de mettre à disposition un manifest (web app
                            manifest) qui va contenir des informations supplémentaires sur
                            l’application. Parmi les champs les plus utilisés dans ce
                            manifeste il va y avoir le nom de l’application, l’icône sous
                            laquelle va être représentée la PWA, l’url utilisée lors du
                            lancement de l’application et enfin le mode d’affichage de la
                            fenêtre.
                        </p>
                    </Box>
                    <Box height="100vh">
                        <h1>Service Worker</h1>
                        <p>
                            Et enfin l’application doit mettre à disposition un service Worker
                            pour permettre à l’application d’être utilisée en mode hors ligne.
                            Nous ne reviendrons pas sur son fonctionnement déjà évoqué
                            ci-dessus.
                        </p>
                    </Box>
                </Container>
            </main>
        </div>
    );
}
