import Head from "next/head";
import { useRouter } from "next/router";
import { Box, Container } from "@mui/material";
import Grid from '@mui/material/Grid';
import ImageList from '@mui/material/ImageList';
import Image from 'next/image'
import ImageListItem from '@mui/material/ImageListItem';
import ImageListItemBar from '@mui/material/ImageListItemBar';
import MenuPres from "../components/Presentation/MenuPres";
import MenuPresItem from "../components/Presentation/MenuPresItem";



export default function Introduction() {

    const itemData = [
        {
            src: '/img/AngularLogo.png',
            title: 'Angular',
        },

        {
            src: "/img/ReactLogo.png",
            title: 'React',
        }
    ]

    return (
        <Container>
            <Head>
                <title>Installation d'une PWA</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Grid container spacing={10} columns={{ sm: 8, md: 12 }}>
                    <Grid item xs={8}>
                        <Container>
                            <h1>Installation d'une PWA</h1>
                            <Box height="auto" marginBottom={10}>
                                <p>Il est extrêmement facile d&apos;installer une PWA. Que vous soyez sur ordinateur,
                                     tablette ou mobile, la méthode est identique.
                                </p>
                            </Box>
                            <Box height="auto" marginBottom={10}>
                                <h2 id="slide2">Sur navigateur</h2>
                                <p>Sur votre navigateur, cliquez sur l&apos;icône :</p>
                                <Image src="/img/dl_icon.png" width={50} height={50}></Image>
                                <p>dans votre barre d'adresse. La PWA sera ensuite installée dans vos applications.</p>
                            </Box>
                            <Box height="auto" marginBottom={10}>
                                <h2>Sur mobile ou tablette</h2>
                                <h3 id="slide3">Android</h3>
                                <h3 id="slide4">IOS / IpadOS</h3>
                                <p>Une fois le site ouvert sur Safari, cliquez sur l&apos;icone :</p>
                                <Image src="/img/share_icon.png" width={23} height={27}></Image>
                                <p>puis cliquez sur <strong>"ajouter à l&apos;écran d'acceuil"</strong>. L&apos;application
                                sera directement ajoutée et accessible depuis votre écran d'acceuil.</p>
                            </Box>
                        </Container>
                    </Grid>
                    <Grid item xs={4}>
                        <Box sx={{
                            display: {
                                xs: "none",
                                md: "block"
                            },
                            position: "sticky",
                            top: "10px",
                        }}>
                            <MenuPres title="Installer une PWA">
                                <MenuPresItem content="Sur ordinateur" linkedElement="#slide2" />
                                <MenuPresItem content="Android" linkedElement="#slide3" />
                                <MenuPresItem content="IOS / IpadOS" linkedElement="#slide4" />
                            </MenuPres>
                        </Box>
                    </Grid>
                </Grid>
            </main>
        </Container >
    )
}
