import Head from "next/head";
import {useRouter} from "next/router";
import {Box, Container} from "@mui/material";
import Grid from '@mui/material/Grid';
import ImageList from '@mui/material/ImageList';
import ImageListItem from '@mui/material/ImageListItem';
import ImageListItemBar from '@mui/material/ImageListItemBar';


export default function Introduction() {
    const router = useRouter();

    const itemData = [
        {
            src: '/img/AngularLogo.png',
            title: 'Angular',
        },

        {
            src: "/img/ReactLogo.png",
            title: 'React',
        }
    ]

    return (
        <Container>
            <Head>
                <title>Outils</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <Box height="100vh" id="mainBox" onClick={() => {
                    router.push("/outils#slide2")
                }}>
                    <Grid container spacing={10} columns={{sm: 8, md: 12}}>
                        <Grid item xs={8}>
                            <h1>Les Outils</h1>
                            <ImageList sx={{width: 400, height: 300}} cols={2} rowHeight={164}>
                                {itemData.map((item) => (
                                    <ImageListItem key={item.img}>
                                        <img
                                            src={`${item.src}?w=164&h=164&fit=crop&auto=format`}
                                            srcSet={`${item.src}?w=248&fit=crop&auto=format&dpr=2 2x`}
                                            alt={item.title}
                                            loading="lazy"
                                        />
                                        <ImageListItemBar position="below" title={item.title}/>
                                    </ImageListItem>
                                ))}
                            </ImageList>
                        </Grid>
                        <Grid item xs={12} md={4}>
                            <h1>React</h1>
                            <p>Il est techniquement possible d&apos;installer n&apos;importe quelle application web en tant que PWA tant qu&apos;elle
                                respecte les critères évoqués ci-dessus. Cependant dans un souci de simplicité il est préconisé d&apos;utiliser
                                des Framework comme React ou Angular mettant en place des applications One Page ou toute l&apos;application est
                                directement livrée au client par le serveur. 
                            </p>
                        </Grid>
                        <Grid item xs={12} md={4}>
                            <h1>Angular</h1>
                            <p>React (développé par Facebook) et Angular (développé par Google)
                                sont deux frameworks JavaScript, références dans le développement web.
                                Ils permettent tous deux de créer des pages web avec différentes interfaces pour l&apos;utilisateur.
                                Les applications web créées à l&apos;aide de ces frameworks sont aussi responsive, c&apos;est à dire, s&apos;adaptent
                                à tous les écrans sur lesquels on souhaite l&apos;afficher.
                            </p>
                        </Grid>
                        <Grid item xs={12} md={4}>
                            <h1>Our Choice</h1>
                            <p>Cependant, certains outils complémentaires viennent s&apos;ajouter à ces frameworks. 
                                Premièrement, NodeJs, un environnement d&apos;exécution pour Javascript fonctionnant en dehors des navigateurs.
                                NodeJs permet aussi de construire des applications plus rapidement que d&apos;autres technologies telles
                                que java, en utilisant moins de lignes de code. 
                            </p>
                        </Grid>
                    </Grid>
                </Box>
            </main>
        </Container>
    )
}